baseURL = "http://camptocamp.github.io/terraboard/"
title = "Terraboard"
languageCode = "en-us"
theme = "elate"

[params]

  #custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Camptocamp"
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Terraboard"
    #home = "<i class='icon-home'></i>Home"
    work = "<i class='icon-camera'></i>Screenshots"
    testimonials = "<i class='icon-bubbles'></i>Testimonials"
    services = "<i class='icon-star'></i>Features"
    about = "<i class='icon-bulb'></i>Other projects"
    contact = "<i class='icon-envelope'></i> Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

  # Hero section
  [params.hero]
    title = "![Terraboard](images/terraboard_logo_only.png) <p>Terraboard</p>"
    subtitle = '''
A Web dashboard to inspect and query Terraform states

[![GitHub stars](https://img.shields.io/github/stars/badges/shields.svg?style=social&logo=github&label=Stars)](https://github.com/camptocamp/terraboard)
[![Docker Pulls](https://img.shields.io/docker/pulls/camptocamp/terraboard.svg)](https://hub.docker.com/r/camptocamp/terraboard/)
[![By Camptocamp](https://img.shields.io/badge/by-camptocamp-fb7047.svg)](http://www.camptocamp.com)
'''

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Install from source"
    description = '''
```shell
$ go get github.com/camptocamp/terraboard
```
'''
    #url = "#"
    #button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Launch with Docker"
    description = '''
```shell
# Set AWS credentials as environment variables:
export AWS_ACCESS_KEY_ID=<access_key>
export AWS_SECRET_ACCESS_KEY=<access_secret>
# Spin up the two containers and a network for them to communciate on:
docker network create terranet
docker run --name db \
  -e POSTGRES_USER=gorm \
  -e POSTGRES_DB=gorm \
  -e POSTGRES_PASSWORD="<mypassword>" \
   --net terranet \
  --restart=always postgres -d
docker run -p 8080:8080 \
 -e AWS_REGION="<region>" \
 -e AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
 -e AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
 -e AWS_BUCKET="<bucket>" \
 -e AWS_DYNAMODB_TABLE="<table>" \
 -e DB_PASSWORD="<mypassword>" \
 --net terranet \
 camptocamp/terraboard:latest
```
'''
    #url = "#"
    #button = "Why us?"
    icon = "icon-rocket"
  #  img = "img_10.jpg"

  #[params.intro.video]
  #  enable = true
  #  title = "Watch the video"
  #  icon = "icon-play2"
  #  url = "https://vimeo.com/channels/staffpicks/93951774"

  # Screenshots section
  [params.work]
    enable = true
    title = "Screenshots"
    description = ""
    footertext = ''

    [[params.work.row]]
      img = "screenshots/main.png"
      alt = "Overview"
      title = "Overview"
      subtitle = "The overview presents all the state files in the S3 bucket, by most recent modification date."

    [[params.work.row]]
      img = "screenshots/state.png"
      alt = "State"
      title = "State View"
      subtitle = "The state view presents details of a Terraform state at a given version."

    [[params.work.row]]
      img = "screenshots/compare.png"
      alt = "Compare"
      title = "Compare View"
      subtitle = "From the state view, you can compare the current state version with another version."

    [[params.work.row]]
      img = "screenshots/search.png"
      alt = "Search"
      title = "Search"
      subtitle = "The search view allows to find resources by various criteria."


  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = ""

    [[params.testimonials.item]]
      quote = '''&ldquo;Terraboard looks cool! I want it to visualize the infra resources of the Federal Spatial Data Infrastructure @swiss_geoportal  @camptocamp #FSDI #Terraform
&rdquo; <br />
	  <span class='subtext'><a href='https://twitter.com/hpchrist/status/934702222105038849'>26 Nov 2017</a></span>'''
      person = 'Christ Hanspeter<span class="subtext"><a href="https://twitter.com/hpchrist" target="_blank"><i class="icon-social-twitter"></i> @hpchrist</a></span>'
      img = "https://pbs.twimg.com/profile_images/488320370/portrait_jp_400x400.JPG"
      alt = "Christ Hanspeter"

    [[params.testimonials.item]]
      quote = '''&ldquo;Terraboard from @raphink a tool for interrogating Terraform remote state looks seriously cool. #cfgmgmtcamp&rdquo; <br />
	  <span class='subtext'><a href='https://twitter.com/sheriffjackson/status/960549930657034241'>6 Feb 2018</a></span>'''
      person = 'Nic Jackson<span class="subtext"><a href="https://twitter.com/sheriffjackson" target="_blank"><i class="icon-social-twitter"></i> @sheriffjackson</a></span>'
      img = "https://pbs.twimg.com/profile_images/839112434501713921/RsZIXY0l_400x400.jpg"
      alt = "Nic Jackson"

    [[params.testimonials.item]]
      quote = '''&ldquo;Thanks @camptocamp for the terraboard! It helps managing infra using @HashiCorp's Terraform at @exoscale. #dogfood&rdquo; <br />
	  <span class='subtext'><a href='https://twitter.com/greut/status/967070987958276097'>23 Feb 2018</a></span>'''
      person = 'Yoan Blanc<span class="subtext"><a href="https://twitter.com/greut" target="_blank"><i class="icon-social-twitter"></i> @greut</a></span>'
      img = "https://pbs.twimg.com/profile_images/57582226/Image_00007_400x400.jpg"
      alt = "Yoan Blanc"


  # Services section
  [params.services]
    enable = true
    title = "Features"
    description = "Terraboard lets you visualize and query Terraform state informations stored in a versioned S3 bucket."

    [[params.services.item]]
      title = "AWS Support"
      description = "Terraboard gets its data from versioned S3 buckets and DynamoDB databases."
      icon = "icon-grid"

    [[params.services.item]]
      title = "Advanced Search"
      description = "Ever wondered in which Terraform project your resources are managed? Terraboard's search interface helps you answer that!"
      icon = "icon-magnifier"

    [[params.services.item]]
      title = "Charts Overview"
      description = "The dashboard features charts with useful stats on your Terraform resources."
      icon = "icon-pie-chart"

    [[params.services.item]]
      title = "Container Ready"
      description = "Terraboard comes packaged as a small container, making it fast and easy to deploy on all container platforms."
      icon = "icon-anchor"

  # About section
  [params.about]
    enable = true
    title = "Other projects"
    description = "We love to contribute Open Source projects at Camptocamp.<br /> Here is a list of some of our most useful tools"

    [[params.about.item]]
      name = "Conplicity"
      position = "Automatic backups for Docker containers"
      description = ""
      img = "conplicity.png"
      alt = "Conplicity"
      social = [
        ["icon-globe", "https://camptocamp.github.io/conplicity"],
        ["icon-github", "https://github.com/camptocamp/conplicity"]
      ]

  # Contact section
  [params.contact]
    enable = true
    form = false
    title = "Contact us!"
    description = "Are you missing features? Would you like consulting, training or other services? Contact us at [info@camptocamp.com](mailto:info@camptocamp.com?subject=Terraboard)!"

  # Footer section
  [params.footer]
    enable = true
    copyright = '[![Camptocamp](images/camptocamp.png)](https://www.camptocamp.com)'
    links = [
        ["icon-globe", "https://www.camptocamp.com"],
        ["icon-twitter", "https://twitter.com/camptocamp"],
        ["icon-github", "https://github.com/camptocamp"]
      ]
